// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "jquery"
import "bootstrap"
import "@fortawesome/fontawesome-free"
import "chart.js"
import "startbootstrap-sb-admin-2"
import "startbootstrap-sb-admin-2-css"
import "jquery-easing"
